--テーブル削除
DROP TABLE BOOKSHELF;

--テーブル作成
CREATE TABLE BOOKSHELF(SEQID INT NOT NULL AUTO_INCREMENT,ID CHAR(5),TITLE char(50) NOT NULL,AUTHORNAME CHAR(50),PUBLISHER CHAR(50) NOT NULL,PROGRESS INT(3),PUBLICATIONDATE date NOT NULL,STARTDATE date,ENDDATE date,EVALUATION INT(4),CREATEDATE date,UPDATEDATE date ,PRIMARY KEY(SEQID,TITLE));
